### PR TITLE
Implement choose_egs_to_merge.py

### PR DESCRIPTION
**Pull request by hhadian**

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks!
I'll merge this without really checking it.  Would you mind starting to (attempt to run) the example script (run_tdnn_1a.sh) and starting to clean up bugs?

**Comment by hhadian** [comment]
I'll give it a try now.

**Comment by danpovey** [comment]
thanks-- please update, I made small changes.

**Comment by hhadian** [comment]
I did. It seems that I can't find `nnet3-adapt` binary. Is it checked in?

**Comment by danpovey** [comment]
forgot to check it in.  just added it.

**Comment by hhadian** [comment]
Thanks, seems that `nnet3a/nnet-chaina-utils.cc` is also missing or maybe not yet implemented?

**Comment by danpovey** [comment]
ok fixed

**Comment by hhadian** [comment]
`NnetChainaBottomTrainer::ComputationStructure::ComputationStructure` seems not implemented

**Comment by danpovey** [comment]
OK, go ahead and implement, it should be trivial, and similar to the same
one in NnetChainaTopTrainer.

**Pull request merged**
