### PR TITLE
xvector: small fix to nnet3-xvector-compute.cc…

### PR DESCRIPTION
**Pull request by david-ryan-snyder**
small fix to nnet3-xvector-compute.cc

### CODE REVIEW

**Comment by danpovey** [comment]
the 'make test' for src/nnet3 is failing in this branch, most likely a bug in the test code itself but please fix.

**Comment by danpovey** [comment]
actually forget this, already fixed it.

**Comment by danpovey** [comment]
BTW, I'm testing with your latest fix, and it doesn't fix the issue that the network is only  evaluating the first half of the xvectors.
i also merged the latest changes from the 'chain' branch.

**Comment by david-ryan-snyder** [comment]
Yes, I'll fix that in the morning.

**Comment by david-ryan-snyder** [comment]
Regarding only using the first half of the xvectors, I am **unable  to reproduce the issue**. These are the steps I took:

1. Create egs with 6 pairs in /home/dsnyder/a16/a16/dsnyder/kaldi/kaldi-xvector2/egs/swbd/s5c/ranges.
image
2. Create the `egs_unmerged.ark` archive from `ranges` and some` feats.scp`.
3. Create two merged egs: `egs_merged6.ark` and `egs_merged3.ark`. The first consists of one minibatch with all 6 egs, and the second is two minibatches with 3 egs each:
image
4. Run the `nnet3-xvector-train` on `egs_merged6.ark` in gdb and verify that there are 12 xvectors in total. This makes sense, since `ranges` had 6 pairs.
image
5. Run the `nnet3-xvector-train` on `egs_merged3.ark` in gdb and verify that there are 6 xvectors in the first minibatch.
image
6. Continue running `nnet3-xvector-train `on `egs_merged3.ark` in gdb and verify that there are 6 xvectors in the second minibatch. Also verify that the first element of `xvector_pairs` in the first and second minibatches are different. 
image

**Comment by danpovey** [comment]
I think I found the problem.  It only happens when the chunk lengths are
different.

  // We only need the output on frame t=0 for each n.


  // So the output index for output node is (n, 0, 0)


  // for n = 0,.., min number of n-values for different t


  // in input indexes.


  // indexes for "s" and "b" output nodes are equal to (0,0,0).

that is not right, it should be the maximum number of n-values for any t
index.
But this is unnecessarily complicated, you can just take the largest n plus
one.
Dan



On Tue, Mar 8, 2016 at 11:46 AM, david-ryan-snyder <notifications@github.com

**Comment by david-ryan-snyder** [comment]
Oh, good catch... I'll rewrite that a bit.

**Pull request merged**
