### PR TITLE
[not-for-merge] Simple thread compiler test

### PR DESCRIPTION
**Pull request by gorinars**
Just to demonstrate that caching now works in TaskSequencer

There is a small fix that should be applied to your commit to fix build, see
 src/nnet3bin/nnet3-xvector-compute.cc

Overall, I compared the results of the executions with several threads including the case when cache is full (see thread-test.sh)
The results of all executions are identical

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks for some very thorough work!!
If you're still awake, would you mind making this PR to the official Kaldi repo?
I'll close it rather than merge it, but please leave the branch in your personal repo, because we may want to point someone to this in future, and if it's to the main kaldi repo, it's more discoverable.

**Comment by gorinars** [comment]
OK. Let me refactor it a bit more then. I'll add the example of using precomputed cache cause this optimization is the one that makes the extractor run much faster. Will do by tomorrow.

**Comment by danpovey** [comment]
You really don't have to change it-- it's more than sufficient as it is.
And you can always make the PR and change it later, since my plan isn't to
merge it, just to keep it for future reference.

**Comment by gorinars** [comment]
Got it. Ok

**Pull request closed without merging**
