### PR TITLE
refactor matrix/vector reader/writers and add `numpy()` to matrix/vector and support zero-copying PyTorch GPU tensors

### PR DESCRIPTION
**Pull request by csukuangfj**
Now there is no extra copy for SequentialReader and it is much
easier to convert a Matrix/Vector to a numpy array.

We can zero-copy a PyTorch GPU tensor to Kaldi with NO dependencies
on PyTorch and it supports any DL frameworks that implement the DLPack interface.

### CODE REVIEW

**Comment by csukuangfj** [comment]
@naxingyu @danpovey 

 please have a review.

**Comment by danpovey** [comment]
Looks very unproblematic to me.  I like the .numpy() thing.  So is the py::array_t actually a NumPy array, or just easily convertible to one?

**Comment by csukuangfj** [comment]
`py::array_t` is a pybind11 class (https://github.com/pybind/pybind11/blob/master/include/pybind11/numpy.h#L831).

I think it can be automagicaly converted to and from numpy.  I'm still learning its internals.

**Comment by csukuangfj** [comment]
I know it is not a good practice to address several issues in a single pullrequest but it makes
my life much easier; I do not need to create multiple branches.

Now it is possible to **ZERO-COPY** PyTorch GPU tensor to Kaldi's  CuSubVector and CuSubMatrix.

Note that there is **NO** dependencies on the PyTorch side.

When [TensorFlow](https://github.com/tensorflow/community/pull/180) also implements
the DLPack interface, there are NO changes needed to be done on the Kaldi side.

Please refer to
 https://github.com/mobvoi/kaldi/blob/fangjun-pybind11/src/pybind/dlpack/dlpack_pybind_test.py
for example usages.

**Comment by danpovey** [comment]
Fantastic!
I'll merge this now as I'm sure it's good, we'll address any issues later.

**Comment by csukuangfj** [comment]
ok, we will go to the official GitHub of kaldi for the next pullrequest.

**Pull request merged**
