### PR TITLE
added nnet-xvector-{training,diagnostics}.{cc,h} to xvector setup.

### PR DESCRIPTION
**Pull request by pegahgh**
I added CopyFromVec function to CuPackedMatrix class. I haven't finished gpu implementation . Do you think do we need this function?

### CODE REVIEW

**Comment by danpovey** [comment]
Regarding CopyFromVec, you would do it as follows (but probably not inline).
[there no need for float/double conversion].

 /// Copy data from a CuVector of size ((NumRows()*(NumRows()+1))/2).
void CopyFromVec(const CuVectorBase<Real> &vec) {
   CuSubVector<Real> this_as_vec(data_,
                                                        (num_rows_ *
(num_rows_ + 1) ) / 2);
    this_as_vec.CopyFromVec(vec);
}

**Comment by danpovey** [comment]
.. and of course you'll see from the implementation why this function isn't
really necessary, as it's easy to do when needed.

**Comment by pegahgh** [comment]
Dear Dan
2nd commit contains nnet-xvector-* files.

**Comment by danpovey** [comment]
I've been thinking about it this morning, and I think it's better if we
create a separate xvector/ and xvectorbin/ directory, and put this stuff
there.  Can you please move the code?
Dan

**Comment by danpovey** [comment]
@pegahgh and @david-ryan-snyder, please talk with each other to co-ordinate your progress!
I am still sick and I don't have as much energy as I'd like.

**Comment by danpovey** [comment]
David, please take note of this-- let's put all xvector related code in
directories xvector and xvectorbin.
Dan

**Comment by pegahgh** [comment]
Dear Dan
I already created xvector and xvectorbin dir and puth all stuff there.

**Comment by pegahgh** [comment]
I plan to write nnet3-xvector-train binary. I wonder if it is fine.

**Comment by danpovey** [comment]
i'll try to resolve the conflicts here and commit

**Comment by danpovey** [comment]
turns out there were no conflicts (not sure why it said there conflicts)
I have pushed these changes, but I have not been reviewing the code carefully.
I'm going to let you make some more progress by yourselves before I look at this, because I'm not feeling well.

**Comment by danpovey** [comment]
sorry did not see this message- of course, it's fine with me.

**Pull request merged**
