### PR TITLE
Minor fixes - nnet3 tests now pass

### PR DESCRIPTION
**Pull request by hhadian**

### CODE REVIEW

**Comment by hhadian** [comment]
Do you want me to start an experiment with this?

**Comment by danpovey** [comment]
Please prepare the scripts.  You can make a tdnnf2 component which uses
that layer type, a specifiable block size (input=output, e.g. 16) and a
specifiable params-per-block (e.g. 64).
Leave the orthonormal-constraint values as they are.  I am working right
now on the code for that, will be done within half an hour.

**Comment by hhadian** [comment]
I'm not sure if you want tdnnf2 to be a layer (like tdnnf-layer, which consists of 4 components (tdnn+tdnn+relu+batchnorm))? Or a component like affine-component?

Alternatively, I can modify the tdnnf-layer to support block-tdnnf.

**Comment by danpovey** [comment]
I mean like tdnnf-layer, just replacing TdnnComponent with
BatchNormalizedTdnnComponent

**Comment by danpovey** [comment]
.. and I have finished the code now.
I haven't done much careful checking, but when you run it, I can see in the
log files whether the orthonormal constraint is working.

**Comment by hhadian** [comment]
I started an experiment on mini-librispeech by replacing all tdnnf-layers with tdnnf2-layers. Is that good?

**Comment by hhadian** [comment]
BTW, I got some warnings of this sort when initializing:
```
WARNING (nnet3-init[5.5.244~3-00ef4]:InitLinearParams():nnet-tdnn-component.cc:910) You specified param-stddev=0.0255155, but we got 64.3773
```

**Comment by danpovey** [comment]
thats good.
I'll look into that warning, it is likely a bug

**Comment by danpovey** [comment]
I fixed that bug.

**Pull request merged**
